### ISSUE TITLE
How to set a specific port ?

### ISSUE THREAD

**Issue by bonzonkim** [javiorfo/nvim-wildcat#1]
just installed Wildcat for my Java project and I just wondering that if I can set a port number in the config file. or any doc of this pulugin?

**Comment by javiorfo** [comment]
Hello, bonzonkim
Port configuration is an application server reponsability. Whether you use JBoss/Wildfly or Tomcat, the port configuration will be done on their respective config xml files (standalone.xml or context.xml).
This keep these application servers decouple from nvim-wildcat
